name: "Prod deployment"

concurrency: 1

on:
  push:
    branches:
      - main

jobs:
  test_package:
    name: "Checkout, Install, and Test"
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      # DATABRICKS_CLUSTER_ID: ${{ secrets.DATABRICKS_CLUSTER_ID }}  # If using Databricks Connect

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install package and dependencies
        run: |
          pip install -e .
          pip install -r requirements-dev.txt

      - name: Run tests
        run: python -m pytest

  deploy:
    name: "Deploy bundle"
    runs-on: ubuntu-latest
    needs: test_package
    environment: prod  # Make sure to configure environment secrets
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.SP_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main

      - name: Configure Databricks CLI
        run: |
          databricks configure --token --host ${{ secrets.DATABRICKS_HOST }} \
            --profile PROD_DEPLOYMENT

      - name: Deploy bundle
        run: databricks bundle deploy -y
        working-directory: .
        env:
          DATABRICKS_BUNDLE_ENV: prod
